version: '3.9'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=auth_service
      - GOOGLE_CLIENT_ID=<your_google_client_id>
      - GOOGLE_SECRET=<your_google_secret>
      - JWT_SECRET=<your_jwt_secret>
    depends_on:
      - postgres
    networks:
      - booking-system-network

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_service
    ports:
      - "15432:5432"
    networks:
      - booking-system-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
