apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: YWRtaW4=   # admin (base64 encoded)
  password: YWRtaW4=   # admin (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth
type: Opaque
data:
  client-id: <your_base64_google_client_id>
  client-secret: <your_base64_google_client_secret>
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: <your_base64_jwt_secret>
